// atoms will consist of direct states
export enum AtomTypes {
  ALL_CHANNELS = 'ALL_CHANNELS',
  ALL_MEMBERS = 'ALL_MEMBERS',
  TEAM_INFO = 'TEAM_INFO',
  CHANNEL_INFO = 'CHANNEL_INFO',
  MEMBER_INFO = 'MEMBER_INFO',
  CHANNEL_MESSAGES = 'CHANNEL_MESSAGES',
  CURRENT_POPUP = 'CURRENT_POPUP',
}