// selectors will consist of derived state
export enum SelectorTypes {
  GENERATE_CHANNELTREE = 'GENERATE_CHANNELTREE',
  GENERATE_MEMBERTREE = 'GENERATE_MEMBERTREE',
  GENERATE_MESSAGETREE = 'GENERATE_MESSAGETREE',
}