// selectors will consist of derived state
export enum SelectorTypes {
  GENERATE_CHANNELTREE = 'GENERATE_CHANNELTREE',
  GENERATE_MEMBERTREE = 'GENERATE_MEMBERTREE',
  GENERATE_CHANNEL_MESSAGETREE = 'GENERATE_CHANNEL_MESSAGETREE',
  GENERATE_DIRECT_MESSAGETREE = 'GENERATE_DIRECT_MESSAGETREE',
}